/// <reference path="../declares.d.ts" />

'use strict';
define(["require", "exports"], function (require, exports) {
    exports.language = {
        displayName: 'Linden Scripting Language (LSL)',
        name: 'lsl',
        mimeTypes: [
            'text/plain;charset=utf-8'
        ],
        fileExtensions: [
            '.lsl'
        ],
        ignoreCase: false,
        editorOptions: {
            tabSize: 4,
            insertSpaces: true
        },
        defaultToken: 'source.lsl',
        lineComment: '//',
        blockCommentStart: '/*',
        blockCommentEnd: '*/',
//      identifier: /[a-zA-Z_][\w$]*/,
//      attributes: [
//      ],
//      accessmodifiers: [
//      ],
        autoClosingPairs: [
            ['{', '}'],
            ['[', ']'],
            ['(', ')'],
            ['<', '>'],
            ['"', '"']
        ],
        operators: [
            ['\+\+', 'keyword.operator.increment.lsl'],
            ['--', 'keyword.operator.decrement.lsl'],
            ['<<', 'keyword.operator.shift.left.lsl'],
            ['>>', 'keyword.operator.shift.right.lsl'],
            ['<=', 'keyword.operator.comparison.less-equal.lsl'],
            ['>=', 'keyword.operator.comparison.greater-equal.lsl'],
            ['&&', 'keyword.operator.logical.and.lsl'],
            ['\|\|', 'keyword.operator.logical.or.lsl'],
            ['~', 'keyword.operator.bit-wise.not.lsl'],
            ['\^', 'keyword.operator.bit-wise.xor.lsl'],
            ['&', 'keyword.operator.bit-wise.and.lsl'],
            ['\|', 'keyword.operator.bit-wise.or.lsl'],
            ['==', 'keyword.operator.comparison.equal.lsl'],
            ['!=', 'keyword.operator.comparison.not.lsl'],
            ['!', 'keyword.operator.logical.not.lsl'],
            ['<', 'keyword.operator.comparison.less.lsl'],
            ['>', 'keyword.operator.comparison.greater.lsl'],
            ['[%*+\/\-]=|=', 'keyword.operator.assignment.augmented.lsl'],
            ['[%*+\/\-]', 'keyword.operator.arithmetic.lsl'],
            [':=', 'invalid.illegal.keyword.operator.unrecognized.wrong-division-assignment.lsl'],
            [':', 'invalid.illegal.keyword.operator.unrecognized.wrong-division.lsl']
        ],
        escapes: [
            ['\\\\', 'constant.character.escape.back-slash.lsl'],
            ['\\n', 'constant.character.escape.new-line.lsl'],
            ['\\t', 'constant.character.escape.tab.lsl'],
            ['\\"', 'constant.character.escape.double-quote.lsl'],
            ['\\.', 'invalid.illegal.constant.character.escape.lsl']
        ],
        brackets: [
            { open: '{', close: '}', token: 'punctuation.definition.bracket.lsl' },
            { open: '(', close: ')', token: 'punctuation.definition.parenthesis.lsl' },
            { open: '[', close: ']', token: 'punctuation.definition.list.lsl' },
            { open: '<', close: '>', token: 'punctuation.definition.angle.lsl' }
        ],
        noindentBrackets: '()',
//      enhancedBrackets: [
//          { tokenType: 'string', openTrigger: '"', open: '"$', closeComplete: '"' },
//          { open: 'at_rot_target', close: '}', matchCase: true },
//          { open: 'at_target', close: '}', matchCase: true },
//          { open: 'attach', close: '}', matchCase: true },
//          { open: 'changed', close: '}', matchCase: true },
//          { open: 'collision', close: '}', matchCase: true },
//          { open: 'collision_end', close: '}', matchCase: true },
//          { open: 'collision_start', close: '}', matchCase: true },
//          { open: 'control', close: '}', matchCase: true },
//          { open: 'dataserver', close: '}', matchCase: true },
//          { open: 'email', close: '}', matchCase: true },
//          { open: 'experience_permissions', close: '}', matchCase: true },
//          { open: 'experience_permissions_denied', close: '}', matchCase: true },
//          { open: 'http_request', close: '}', matchCase: true },
//          { open: 'http_response', close: '}', matchCase: true },
//          { open: 'land_collision', close: '}', matchCase: true },
//          { open: 'land_collision_end', close: '}', matchCase: true },
//          { open: 'land_collision_start', close: '}', matchCase: true },
//          { open: 'link_message', close: '}', matchCase: true },
//          { open: 'listen', close: '}', matchCase: true },
//          { open: 'money', close: '}', matchCase: true },
//          { open: 'moving_end', close: '}', matchCase: true },
//          { open: 'moving_start', close: '}', matchCase: true },
//          { open: 'no_sensor', close: '}', matchCase: true },
//          { open: 'not_at_rot_target', close: '}', matchCase: true },
//          { open: 'not_at_target', close: '}', matchCase: true },
//          { open: 'object_rez', close: '}', matchCase: true },
//          { open: 'on_rez', close: '}', matchCase: true },
//          { open: 'path_update', close: '}', matchCase: true },
//          { open: 'remote_data', close: '}', matchCase: true },
//          { open: 'run_time_permissions', close: '}', matchCase: true },
//          { open: 'sensor', close: '}', matchCase: true },
//          { open: 'state_entry', close: '}', matchCase: true },
//          { open: 'state_exit', close: '}', matchCase: true },
//          { open: 'timer', close: '}', matchCase: true },
//          { open: 'touch', close: '}', matchCase: true },
//          { open: 'touch_end', close: '}', matchCase: true },
//          { open: 'touch_start', close: '}', matchCase: true },
//          { open: 'transaction_result', close: '}', matchCase: true }
//      ],
        parenFollows: [
            'else',
            'for',
            'if'
        ],
        LSL_Event: [
            'at_rot_target',
            'at_target',
            'attach',
            'changed',
            'collision',
            'collision_end',
            'collision_start',
            'control',
            'dataserver',
            'email',
            'experience_permissions',
            'experience_permissions_denied',
            'http_request',
            'http_response',
            'land_collision',
            'land_collision_end',
            'land_collision_start',
            'link_message',
            'listen',
            'money',
            'moving_end',
            'moving_start',
            'no_sensor',
            'not_at_rot_target',
            'not_at_target',
            'object_rez',
            'on_rez',
            'path_update',
            'remote_data',
            'run_time_permissions',
            'sensor',
            'state_entry',
            'state_exit',
            'timer',
            'touch',
            'touch_end',
            'touch_start',
            'transaction_result'
        ],
        LSL_FlowControl: [
            'do',
            'else',
            'for',
            'if',
            'jump',
            'return',
            'while'
        ],
        LSL_StorageType: [
            'float',
            'integer',
            'key',
            'list',
            'quaternion',
            'rotation',
            'string',
            'vector'
        ],
        LSL_ConstantFloat: [
            'DEG_TO_RAD',
            'PI',
            'PI_BY_TWO',
            'RAD_TO_DEG',
            'SQRT2',
            'TWO_PI'
        ],
        LSL_ConstantInteger: [
            'ACTIVE',
            'AGENT',
            'AGENT_ALWAYS_RUN',
            'AGENT_ATTACHMENTS',
            'AGENT_AUTOPILOT',
            'AGENT_AWAY',
            'AGENT_BUSY',
            'AGENT_BY_LEGACY_NAME',
            'AGENT_BY_USERNAME',
            'AGENT_CROUCHING',
            'AGENT_FLYING',
            'AGENT_IN_AIR',
            'AGENT_LIST_PARCEL',
            'AGENT_LIST_PARCEL_OWNER',
            'AGENT_LIST_REGION',
            'AGENT_MOUSELOOK',
            'AGENT_ON_OBJECT',
            'AGENT_SCRIPTED',
            'AGENT_SITTING',
            'AGENT_TYPING',
            'AGENT_WALKING',
            'ALL_SIDES',
            'ANIM_ON',
            'ATTACH_AVATAR_CENTER',
            'ATTACH_BACK',
            'ATTACH_BELLY',
            'ATTACH_CHEST',
            'ATTACH_CHIN',
            'ATTACH_HEAD',
            'ATTACH_HUD_BOTTOM',
            'ATTACH_HUD_BOTTOM_LEFT',
            'ATTACH_HUD_BOTTOM_RIGHT',
            'ATTACH_HUD_CENTER_1',
            'ATTACH_HUD_CENTER_2',
            'ATTACH_HUD_TOP_CENTER',
            'ATTACH_HUD_TOP_LEFT',
            'ATTACH_HUD_TOP_RIGHT',
            'ATTACH_LEAR',
            'ATTACH_LEFT_PEC',
            'ATTACH_LEYE',
            'ATTACH_LFOOT',
            'ATTACH_LHAND',
            'ATTACH_LHIP',
            'ATTACH_LLARM',
            'ATTACH_LLLEG',
            'ATTACH_LSHOULDER',
            'ATTACH_LUARM',
            'ATTACH_LULEG',
            'ATTACH_MOUTH',
            'ATTACH_NECK',
            'ATTACH_NOSE',
            'ATTACH_PELVIS',
            'ATTACH_REAR',
            'ATTACH_REYE',
            'ATTACH_RFOOT',
            'ATTACH_RHAND',
            'ATTACH_RHIP',
            'ATTACH_RIGHT_PEC',
            'ATTACH_RLARM',
            'ATTACH_RLLEG',
            'ATTACH_RSHOULDER',
            'ATTACH_RUARM',
            'ATTACH_RULEG',
            'AVOID_CHARACTERS',
            'AVOID_DYNAMIC_OBSTACLES',
            'AVOID_NONE',
            'CAMERA_ACTIVE',
            'CAMERA_BEHINDNESS_ANGLE',
            'CAMERA_BEHINDNESS_LAG',
            'CAMERA_DISTANCE',
            'CAMERA_FOCUS',
            'CAMERA_FOCUS_LAG',
            'CAMERA_FOCUS_LOCKED',
            'CAMERA_FOCUS_OFFSET',
            'CAMERA_FOCUS_THRESHOLD',
            'CAMERA_PITCH',
            'CAMERA_POSITION',
            'CAMERA_POSITION_LAG',
            'CAMERA_POSITION_LOCKED',
            'CAMERA_POSITION_THRESHOLD',
            'CHANGED_ALLOWED_DROP',
            'CHANGED_COLOR',
            'CHANGED_INVENTORY',
            'CHANGED_LINK',
            'CHANGED_MEDIA',
            'CHANGED_OWNER',
            'CHANGED_REGION',
            'CHANGED_REGION_START',
            'CHANGED_SCALE',
            'CHANGED_SHAPE',
            'CHANGED_TELEPORT',
            'CHANGED_TEXTURE',
            'CHARACTER_ACCOUNT_FOR_SKIPPED_FRAMES',
            'CHARACTER_AVOIDANCE_MODE',
            'CHARACTER_CMD_JUMP',
            'CHARACTER_CMD_SMOOTH_STOP',
            'CHARACTER_CMD_STOP',
            'CHARACTER_DESIRED_SPEED',
            'CHARACTER_DESIRED_TURN_SPEED',
            'CHARACTER_LENGTH',
            'CHARACTER_MAX_ACCEL',
            'CHARACTER_MAX_DECEL',
            'CHARACTER_MAX_SPEED',
            'CHARACTER_MAX_TURN_RADIUS',
            'CHARACTER_ORIENTATION',
            'CHARACTER_RADIUS',
            'CHARACTER_STAY_WITHIN_PARCEL',
            'CHARACTER_TYPE',
            'CHARACTER_TYPE_A',
            'CHARACTER_TYPE_B',
            'CHARACTER_TYPE_C',
            'CHARACTER_TYPE_D',
            'CHARACTER_TYPE_NONE',
            'CLICK_ACTION_BUY',
            'CLICK_ACTION_NONE',
            'CLICK_ACTION_OPEN',
            'CLICK_ACTION_OPEN_MEDIA',
            'CLICK_ACTION_PAY',
            'CLICK_ACTION_PLAY',
            'CLICK_ACTION_SIT',
            'CLICK_ACTION_TOUCH',
            'CONTENT_TYPE_ATOM',
            'CONTENT_TYPE_FORM',
            'CONTENT_TYPE_HTML',
            'CONTENT_TYPE_JSON',
            'CONTENT_TYPE_LLSD',
            'CONTENT_TYPE_RSS',
            'CONTENT_TYPE_TEXT',
            'CONTENT_TYPE_XHTML',
            'CONTENT_TYPE_XML',
            'CONTROL_BACK',
            'CONTROL_DOWN',
            'CONTROL_FWD',
            'CONTROL_LBUTTON',
            'CONTROL_LEFT',
            'CONTROL_ML_LBUTTON',
            'CONTROL_RIGHT',
            'CONTROL_ROT_LEFT',
            'CONTROL_ROT_RIGHT',
            'CONTROL_UP',
            'DATA_BORN',
            'DATA_NAME',
            'DATA_ONLINE',
            'DATA_PAYINFO',
            'DATA_SIM_POS',
            'DATA_SIM_RATING',
            'DATA_SIM_STATUS',
            'DEBUG_CHANNEL',
            'DENSITY',
            'ERR_GENERIC',
            'ERR_MALFORMED_PARAMS',
            'ERR_PARCEL_PERMISSIONS',
            'ERR_RUNTIME_PERMISSIONS',
            'ERR_THROTTLED',
            'ESTATE_ACCESS_ALLOWED_AGENT_ADD',
            'ESTATE_ACCESS_ALLOWED_AGENT_REMOVE',
            'ESTATE_ACCESS_ALLOWED_GROUP_ADD',
            'ESTATE_ACCESS_ALLOWED_GROUP_REMOVE',
            'ESTATE_ACCESS_BANNED_AGENT_ADD',
            'ESTATE_ACCESS_BANNED_AGENT_REMOVE',
            'FORCE_DIRECT_PATH',
            'FRICTION',
            'GCNP_RADIUS',
            'GCNP_STATIC',
            'GRAVITY_MULTIPLIER',
            'HORIZONTAL',
            'HTTP_BODY_MAXLENGTH',
            'HTTP_BODY_TRUNCATED',
            'HTTP_CUSTOM_HEADER',
            'HTTP_METHOD',
            'HTTP_MIMETYPE',
            'HTTP_PRAGMA_NO_CACHE',
            'HTTP_VERBOSE_THROTTLE',
            'HTTP_VERIFY_CERT',
            'INVENTORY_ALL',
            'INVENTORY_ANIMATION',
            'INVENTORY_BODYPART',
            'INVENTORY_CLOTHING',
            'INVENTORY_GESTURE',
            'INVENTORY_LANDMARK',
            'INVENTORY_NONE',
            'INVENTORY_NOTECARD',
            'INVENTORY_OBJECT',
            'INVENTORY_SCRIPT',
            'INVENTORY_SOUND',
            'INVENTORY_TEXTURE',
            'JSON_APPEND',
            'KFM_CMD_PAUSE',
            'KFM_CMD_PLAY',
            'KFM_CMD_SET_MODE',
            'KFM_CMD_STOP',
            'KFM_COMMAND',
            'KFM_DATA',
            'KFM_FORWARD',
            'KFM_LOOP',
            'KFM_MODE',
            'KFM_PING_PONG',
            'KFM_REVERSE',
            'KFM_ROTATION',
            'KFM_TRANSLATION',
            'LAND_LEVEL',
            'LAND_LOWER',
            'LAND_NOISE',
            'LAND_RAISE',
            'LAND_REVERT',
            'LAND_SMOOTH',
            'LINK_ALL_CHILDREN',
            'LINK_ALL_OTHERS',
            'LINK_ROOT',
            'LINK_SET',
            'LINK_THIS',
            'LIST_STAT_GEOMETRIC_MEAN',
            'LIST_STAT_MAX',
            'LIST_STAT_MEAN',
            'LIST_STAT_MEDIAN',
            'LIST_STAT_MIN',
            'LIST_STAT_NUM_COUNT',
            'LIST_STAT_RANGE',
            'LIST_STAT_STD_DEV',
            'LIST_STAT_SUM',
            'LIST_STAT_SUM_SQUARES',
            'LOOP',
            'MASK_BASE',
            'MASK_EVERYONE',
            'MASK_GROUP',
            'MASK_NEXT',
            'MASK_OWNER',
            'OBJECT_ATTACHED_POINT',
            'OBJECT_BODY_SHAPE_TYPE',
            'OBJECT_CHARACTER_TIME',
            'OBJECT_CLICK_ACTION',
            'OBJECT_CREATOR',
            'OBJECT_DESC',
            'OBJECT_GROUP',
            'OBJECT_HOVER_HEIGHT',
            'OBJECT_LAST_OWNER_ID',
            'OBJECT_NAME',
            'OBJECT_OWNER',
            'OBJECT_PATHFINDING_TYPE',
            'OBJECT_PHANTOM',
            'OBJECT_PHYSICS',
            'OBJECT_PHYSICS_COST',
            'OBJECT_POS',
            'OBJECT_PRIM_EQUIVALENCE',
            'OBJECT_RENDER_WEIGHT',
            'OBJECT_RETURN_PARCEL',
            'OBJECT_RETURN_PARCEL_OWNER',
            'OBJECT_RETURN_REGION',
            'OBJECT_ROOT',
            'OBJECT_ROT',
            'OBJECT_RUNNING_SCRIPT_COUNT',
            'OBJECT_SCRIPT_MEMORY',
            'OBJECT_SCRIPT_TIME',
            'OBJECT_SERVER_COST',
            'OBJECT_STREAMING_COST',
            'OBJECT_TEMP_ON_REZ',
            'OBJECT_TOTAL_SCRIPT_COUNT',
            'OBJECT_UNKNOWN_DETAIL',
            'OBJECT_VELOCITY',
            'OPT_AVATAR',
            'OPT_CHARACTER',
            'OPT_EXCLUSION_VOLUME',
            'OPT_LEGACY_LINKSET',
            'OPT_MATERIAL_VOLUME',
            'OPT_OTHER',
            'OPT_STATIC_OBSTACLE',
            'OPT_WALKABLE',
            'PARCEL_COUNT_GROUP',
            'PARCEL_COUNT_OTHER',
            'PARCEL_COUNT_OWNER',
            'PARCEL_COUNT_SELECTED',
            'PARCEL_COUNT_TEMP',
            'PARCEL_COUNT_TOTAL',
            'PARCEL_DETAILS_AREA',
            'PARCEL_DETAILS_DESC',
            'PARCEL_DETAILS_GROUP',
            'PARCEL_DETAILS_ID',
            'PARCEL_DETAILS_NAME',
            'PARCEL_DETAILS_OWNER',
            'PARCEL_DETAILS_SEE_AVATARS',
            'PARCEL_FLAG_ALLOW_ALL_OBJECT_ENTRY',
            'PARCEL_FLAG_ALLOW_CREATE_GROUP_OBJECTS',
            'PARCEL_FLAG_ALLOW_CREATE_OBJECTS',
            'PARCEL_FLAG_ALLOW_DAMAGE',
            'PARCEL_FLAG_ALLOW_FLY',
            'PARCEL_FLAG_ALLOW_GROUP_OBJECT_ENTRY',
            'PARCEL_FLAG_ALLOW_GROUP_SCRIPTS',
            'PARCEL_FLAG_ALLOW_LANDMARK',
            'PARCEL_FLAG_ALLOW_SCRIPTS',
            'PARCEL_FLAG_ALLOW_TERRAFORM',
            'PARCEL_FLAG_LOCAL_SOUND_ONLY',
            'PARCEL_FLAG_RESTRICT_PUSHOBJECT',
            'PARCEL_FLAG_USE_ACCESS_GROUP',
            'PARCEL_FLAG_USE_ACCESS_LIST',
            'PARCEL_FLAG_USE_BAN_LIST',
            'PARCEL_FLAG_USE_LAND_PASS_LIST',
            'PARCEL_MEDIA_COMMAND_AGENT',
            'PARCEL_MEDIA_COMMAND_AUTO_ALIGN',
            'PARCEL_MEDIA_COMMAND_DESC',
            'PARCEL_MEDIA_COMMAND_LOOP',
            'PARCEL_MEDIA_COMMAND_LOOP_SET',
            'PARCEL_MEDIA_COMMAND_PAUSE',
            'PARCEL_MEDIA_COMMAND_PLAY',
            'PARCEL_MEDIA_COMMAND_SIZE',
            'PARCEL_MEDIA_COMMAND_STOP',
            'PARCEL_MEDIA_COMMAND_TEXTURE',
            'PARCEL_MEDIA_COMMAND_TIME',
            'PARCEL_MEDIA_COMMAND_TYPE',
            'PARCEL_MEDIA_COMMAND_UNLOAD',
            'PARCEL_MEDIA_COMMAND_URL',
            'PASS_ALWAYS',
            'PASS_IF_NOT_HANDLED',
            'PASS_NEVER',
            'PASSIVE',
            'PATROL_PAUSE_AT_WAYPOINTS',
            'PAYMENT_INFO_ON_FILE',
            'PAYMENT_INFO_USED',
            'PAY_DEFAULT',
            'PAY_HIDE',
            'PERMISSION_ATTACH',
            'PERMISSION_CHANGE_LINKS',
            'PERMISSION_CONTROL_CAMERA',
            'PERMISSION_DEBIT',
            'PERMISSION_OVERRIDE_ANIMATIONS',
            'PERMISSION_RETURN_OBJECTS',
            'PERMISSION_SILENT_ESTATE_MANAGEMENT',
            'PERMISSION_TAKE_CONTROLS',
            'PERMISSION_TELEPORT',
            'PERMISSION_TRACK_CAMERA',
            'PERMISSION_TRIGGER_ANIMATION',
            'PERM_ALL',
            'PERM_COPY',
            'PERM_MODIFY',
            'PERM_MOVE',
            'PERM_TRANSFER',
            'PING_PONG',
            'PRIM_ALPHA_MODE',
            'PRIM_ALPHA_MODE_BLEND',
            'PRIM_ALPHA_MODE_EMISSIVE',
            'PRIM_ALPHA_MODE_MASK',
            'PRIM_ALPHA_MODE_NONE',
            'PRIM_BUMP_BARK',
            'PRIM_BUMP_BLOBS',
            'PRIM_BUMP_BRICKS',
            'PRIM_BUMP_BRIGHT',
            'PRIM_BUMP_CHECKER',
            'PRIM_BUMP_CONCRETE',
            'PRIM_BUMP_DARK',
            'PRIM_BUMP_DISKS',
            'PRIM_BUMP_GRAVEL',
            'PRIM_BUMP_LARGETILE',
            'PRIM_BUMP_NONE',
            'PRIM_BUMP_SHINY',
            'PRIM_BUMP_SIDING',
            'PRIM_BUMP_STONE',
            'PRIM_BUMP_STUCCO',
            'PRIM_BUMP_SUCTION',
            'PRIM_BUMP_TILE',
            'PRIM_BUMP_WEAVE',
            'PRIM_BUMP_WOOD',
            'PRIM_COLOR',
            'PRIM_DESC',
            'PRIM_FLEXIBLE',
            'PRIM_FULLBRIGHT',
            'PRIM_GLOW',
            'PRIM_HOLE_CIRCLE',
            'PRIM_HOLE_DEFAULT',
            'PRIM_HOLE_SQUARE',
            'PRIM_HOLE_TRIANGLE',
            'PRIM_LINK_TARGET',
            'PRIM_MATERIAL',
            'PRIM_MATERIAL_FLESH',
            'PRIM_MATERIAL_GLASS',
            'PRIM_MATERIAL_METAL',
            'PRIM_MATERIAL_PLASTIC',
            'PRIM_MATERIAL_RUBBER',
            'PRIM_MATERIAL_STONE',
            'PRIM_MATERIAL_WOOD',
            'PRIM_MEDIA_ALT_IMAGE_ENABLE',
            'PRIM_MEDIA_AUTO_LOOP',
            'PRIM_MEDIA_AUTO_PLAY',
            'PRIM_MEDIA_AUTO_SCALE',
            'PRIM_MEDIA_AUTO_ZOOM',
            'PRIM_MEDIA_CONTROLS',
            'PRIM_MEDIA_CONTROLS_MINI',
            'PRIM_MEDIA_CONTROLS_STANDARD',
            'PRIM_MEDIA_CURRENT_URL',
            'PRIM_MEDIA_FIRST_CLICK_INTERACT',
            'PRIM_MEDIA_HEIGHT_PIXELS',
            'PRIM_MEDIA_HOME_URL',
            'PRIM_MEDIA_MAX_HEIGHT_PIXELS',
            'PRIM_MEDIA_MAX_URL_LENGTH',
            'PRIM_MEDIA_MAX_WHITELIST_COUNT',
            'PRIM_MEDIA_MAX_WHITELIST_SIZE',
            'PRIM_MEDIA_MAX_WIDTH_PIXELS',
            'PRIM_MEDIA_PARAM_MAX',
            'PRIM_MEDIA_PERMS_CONTROL',
            'PRIM_MEDIA_PERMS_INTERACT',
            'PRIM_MEDIA_PERM_ANYONE',
            'PRIM_MEDIA_PERM_GROUP',
            'PRIM_MEDIA_PERM_NONE',
            'PRIM_MEDIA_PERM_OWNER',
            'PRIM_MEDIA_WHITELIST',
            'PRIM_MEDIA_WHITELIST_ENABLE',
            'PRIM_MEDIA_WIDTH_PIXELS',
            'PRIM_NAME',
            'PRIM_NORMAL',
            'PRIM_OMEGA',
            'PRIM_PHANTOM',
            'PRIM_PHYSICS',
            'PRIM_PHYSICS_SHAPE_CONVEX',
            'PRIM_PHYSICS_SHAPE_NONE',
            'PRIM_PHYSICS_SHAPE_PRIM',
            'PRIM_PHYSICS_SHAPE_TYPE',
            'PRIM_POINT_LIGHT',
            'PRIM_POSITION',
            'PRIM_POS_LOCAL',
            'PRIM_ROTATION',
            'PRIM_ROT_LOCAL',
            'PRIM_SCULPT_FLAG_INVERT',
            'PRIM_SCULPT_FLAG_MIRROR',
            'PRIM_SCULPT_TYPE_CYLINDER',
            'PRIM_SCULPT_TYPE_MASK',
            'PRIM_SCULPT_TYPE_PLANE',
            'PRIM_SCULPT_TYPE_SPHERE',
            'PRIM_SCULPT_TYPE_TORUS',
            'PRIM_SHINY_HIGH',
            'PRIM_SHINY_LOW',
            'PRIM_SHINY_MEDIUM',
            'PRIM_SHINY_NONE',
            'PRIM_SIZE',
            'PRIM_SLICE',
            'PRIM_SPECULAR',
            'PRIM_TEMP_ON_REZ',
            'PRIM_TEXGEN',
            'PRIM_TEXGEN_DEFAULT',
            'PRIM_TEXGEN_PLANAR',
            'PRIM_TEXT',
            'PRIM_TEXTURE',
            'PRIM_TYPE',
            'PRIM_TYPE_BOX',
            'PRIM_TYPE_CYLINDER',
            'PRIM_TYPE_PRISM',
            'PRIM_TYPE_RING',
            'PRIM_TYPE_SCULPT',
            'PRIM_TYPE_SPHERE',
            'PRIM_TYPE_TORUS',
            'PRIM_TYPE_TUBE',
            'PROFILE_NONE',
            'PROFILE_SCRIPT_MEMORY',
            'PSYS_PART_BF_DEST_COLOR',
            'PSYS_PART_BF_ONE',
            'PSYS_PART_BF_ONE_MINUS_DEST_COLOR',
            'PSYS_PART_BF_ONE_MINUS_SOURCE_ALPHA',
            'PSYS_PART_BF_ONE_MINUS_SOURCE_COLOR',
            'PSYS_PART_BF_SOURCE_ALPHA',
            'PSYS_PART_BF_SOURCE_COLOR',
            'PSYS_PART_BF_ZERO',
            'PSYS_PART_BLEND_FUNC_DEST',
            'PSYS_PART_BLEND_FUNC_SOURCE',
            'PSYS_PART_BOUNCE_MASK',
            'PSYS_PART_EMISSIVE_MASK',
            'PSYS_PART_END_ALPHA',
            'PSYS_PART_END_COLOR',
            'PSYS_PART_END_GLOW',
            'PSYS_PART_END_SCALE',
            'PSYS_PART_FLAGS',
            'PSYS_PART_FOLLOW_SRC_MASK',
            'PSYS_PART_FOLLOW_VELOCITY_MASK',
            'PSYS_PART_INTERP_COLOR_MASK',
            'PSYS_PART_INTERP_SCALE_MASK',
            'PSYS_PART_MAX_AGE',
            'PSYS_PART_RIBBON_MASK',
            'PSYS_PART_START_ALPHA',
            'PSYS_PART_START_COLOR',
            'PSYS_PART_START_GLOW',
            'PSYS_PART_START_SCALE',
            'PSYS_PART_TARGET_LINEAR_MASK',
            'PSYS_PART_TARGET_POS_MASK',
            'PSYS_PART_WIND_MASK',
            'PSYS_SRC_ACCEL',
            'PSYS_SRC_ANGLE_BEGIN',
            'PSYS_SRC_ANGLE_END',
            'PSYS_SRC_BURST_PART_COUNT',
            'PSYS_SRC_BURST_RADIUS',
            'PSYS_SRC_BURST_RATE',
            'PSYS_SRC_BURST_SPEED_MAX',
            'PSYS_SRC_BURST_SPEED_MIN',
            'PSYS_SRC_MAX_AGE',
            'PSYS_SRC_OMEGA',
            'PSYS_SRC_PATTERN',
            'PSYS_SRC_PATTERN_ANGLE',
            'PSYS_SRC_PATTERN_ANGLE_CONE',
            'PSYS_SRC_PATTERN_ANGLE_CONE_EMPTY',
            'PSYS_SRC_PATTERN_DROP',
            'PSYS_SRC_PATTERN_EXPLODE',
            'PSYS_SRC_TARGET_KEY',
            'PSYS_SRC_TEXTURE',
            'PUBLIC_CHANNEL',
            'PURSUIT_FUZZ_FACTOR',
            'PURSUIT_GOAL_TOLERANCE',
            'PURSUIT_INTERCEPT',
            'PURSUIT_OFFSET',
            'PU_EVADE_HIDDEN',
            'PU_EVADE_SPOTTED',
            'PU_FAILURE_DYNAMIC_PATHFINDING_DISABLED',
            'PU_FAILURE_INVALID_GOAL',
            'PU_FAILURE_INVALID_START',
            'PU_FAILURE_NO_NAVMESH',
            'PU_FAILURE_NO_VALID_DESTINATION',
            'PU_FAILURE_OTHER',
            'PU_FAILURE_PARCEL_UNREACHABLE',
            'PU_FAILURE_TARGET_GONE',
            'PU_FAILURE_UNREACHABLE',
            'PU_GOAL_REACHED',
            'PU_SLOWDOWN_DISTANCE_REACHED',
            'RCERR_CAST_TIME_EXCEEDED',
            'RCERR_SIM_PERF_LOW',
            'RCERR_UNKNOWN',
            'RC_DATA_FLAGS',
            'RC_DETECT_PHANTOM',
            'RC_GET_LINK_NUM',
            'RC_GET_NORMAL',
            'RC_GET_ROOT_KEY',
            'RC_MAX_HITS',
            'RC_REJECT_AGENTS',
            'RC_REJECT_LAND',
            'RC_REJECT_NONPHYSICAL',
            'RC_REJECT_PHYSICAL',
            'RC_REJECT_TYPES',
            'REGION_FLAG_ALLOW_DAMAGE',
            'REGION_FLAG_ALLOW_DIRECT_TELEPORT',
            'REGION_FLAG_BLOCK_FLY',
            'REGION_FLAG_BLOCK_TERRAFORM',
            'REGION_FLAG_DISABLE_COLLISIONS',
            'REGION_FLAG_DISABLE_PHYSICS',
            'REGION_FLAG_FIXED_SUN',
            'REGION_FLAG_RESTRICT_PUSHOBJECT',
            'REGION_FLAG_SANDBOX',
            'REMOTE_DATA_CHANNEL',
            'REMOTE_DATA_REPLY',
            'REMOTE_DATA_REQUEST',
            'REQUIRE_LINE_OF_SIGHT',
            'RESTITUTION',
            'REVERSE',
            'ROTATE',
            'SCALE',
            'SCRIPTED',
            'SIM_STAT_PCT_CHARS_STEPPED',
            'SMOOTH',
            'STATUS_BLOCK_GRAB',
            'STATUS_BLOCK_GRAB_OBJECT',
            'STATUS_BOUNDS_ERROR',
            'STATUS_CAST_SHADOWS',
            'STATUS_DIE_AT_EDGE',
            'STATUS_INTERNAL_ERROR',
            'STATUS_MALFORMED_PARAMS',
            'STATUS_NOT_FOUND',
            'STATUS_NOT_SUPPORTED',
            'STATUS_OK',
            'STATUS_PHANTOM',
            'STATUS_PHYSICS',
            'STATUS_RETURN_AT_EDGE',
            'STATUS_ROTATE_X',
            'STATUS_ROTATE_Y',
            'STATUS_ROTATE_Z',
            'STATUS_SANDBOX',
            'STATUS_TYPE_MISMATCH',
            'STATUS_WHITELIST_FAILED',
            'STRING_TRIM',
            'STRING_TRIM_HEAD',
            'STRING_TRIM_TAIL',
            'TOUCH_INVALID_FACE',
            'TRAVERSAL_TYPE',
            'TRAVERSAL_TYPE_FAST',
            'TRAVERSAL_TYPE_NONE',
            'TRAVERSAL_TYPE_SLOW',
            'TYPE_FLOAT',
            'TYPE_INTEGER',
            'TYPE_INVALID',
            'TYPE_KEY',
            'TYPE_ROTATION',
            'TYPE_STRING',
            'TYPE_VECTOR',
            'VEHICLE_ANGULAR_DEFLECTION_EFFICIENCY',
            'VEHICLE_ANGULAR_DEFLECTION_TIMESCALE',
            'VEHICLE_ANGULAR_FRICTION_TIMESCALE',
            'VEHICLE_ANGULAR_MOTOR_DECAY_TIMESCALE',
            'VEHICLE_ANGULAR_MOTOR_DIRECTION',
            'VEHICLE_ANGULAR_MOTOR_TIMESCALE',
            'VEHICLE_BANKING_EFFICIENCY',
            'VEHICLE_BANKING_MIX',
            'VEHICLE_BANKING_TIMESCALE',
            'VEHICLE_BUOYANCY',
            'VEHICLE_FLAG_CAMERA_DECOUPLED',
            'VEHICLE_FLAG_HOVER_GLOBAL_HEIGHT',
            'VEHICLE_FLAG_HOVER_TERRAIN_ONLY',
            'VEHICLE_FLAG_HOVER_UP_ONLY',
            'VEHICLE_FLAG_HOVER_WATER_ONLY',
            'VEHICLE_FLAG_LIMIT_MOTOR_UP',
            'VEHICLE_FLAG_LIMIT_ROLL_ONLY',
            'VEHICLE_FLAG_MOUSELOOK_BANK',
            'VEHICLE_FLAG_MOUSELOOK_STEER',
            'VEHICLE_FLAG_NO_DEFLECTION_UP',
            'VEHICLE_HOVER_EFFICIENCY',
            'VEHICLE_HOVER_HEIGHT',
            'VEHICLE_HOVER_TIMESCALE',
            'VEHICLE_LINEAR_DEFLECTION_EFFICIENCY',
            'VEHICLE_LINEAR_DEFLECTION_TIMESCALE',
            'VEHICLE_LINEAR_FRICTION_TIMESCALE',
            'VEHICLE_LINEAR_MOTOR_DECAY_TIMESCALE',
            'VEHICLE_LINEAR_MOTOR_DIRECTION',
            'VEHICLE_LINEAR_MOTOR_OFFSET',
            'VEHICLE_LINEAR_MOTOR_TIMESCALE',
            'VEHICLE_REFERENCE_FRAME',
            'VEHICLE_TYPE_AIRPLANE',
            'VEHICLE_TYPE_BALLOON',
            'VEHICLE_TYPE_BOAT',
            'VEHICLE_TYPE_CAR',
            'VEHICLE_TYPE_NONE',
            'VEHICLE_TYPE_SLED',
            'VEHICLE_VERTICAL_ATTRACTION_EFFICIENCY',
            'VEHICLE_VERTICAL_ATTRACTION_TIMESCALE',
            'VERTICAL',
            'WANDER_PAUSE_AT_WAYPOINTS',
            'XP_ERROR_EXPERIENCES_DISABLED',
            'XP_ERROR_EXPERIENCE_DISABLED',
            'XP_ERROR_EXPERIENCE_SUSPENDED',
            'XP_ERROR_INVALID_EXPERIENCE',
            'XP_ERROR_INVALID_PARAMETERS',
            'XP_ERROR_KEY_NOT_FOUND',
            'XP_ERROR_MATURITY_EXCEEDED',
            'XP_ERROR_NONE',
            'XP_ERROR_NOT_FOUND',
            'XP_ERROR_NOT_PERMITTED',
            'XP_ERROR_NOT_PERMITTED_LAND',
            'XP_ERROR_NO_EXPERIENCE',
            'XP_ERROR_QUOTA_EXCEEDED',
            'XP_ERROR_RETRY_UPDATE',
            'XP_ERROR_STORAGE_EXCEPTION',
            'XP_ERROR_STORE_DISABLED',
            'XP_ERROR_THROTTLED',
            'XP_ERROR_UNKNOWN_ERROR'
        ],
        LSL_ConstantIntegerBoolean: [
            'FALSE',
            'TRUE'
        ],
        LSL_ConstantRotation: [
            'ZERO_ROTATION'
        ],
        LSL_ConstantString: [
            'EOF',
            'JSON_ARRAY',
            'JSON_DELETE',
            'JSON_FALSE',
            'JSON_INVALID',
            'JSON_NULL',
            'JSON_NUMBER',
            'JSON_OBJECT',
            'JSON_STRING',
            'JSON_TRUE',
            'NULL_KEY',
            'TEXTURE_BLANK',
            'TEXTURE_DEFAULT',
            'TEXTURE_MEDIA',
            'TEXTURE_PLYWOOD',
            'TEXTURE_TRANSPARENT',
            'URL_REQUEST_DENIED',
            'URL_REQUEST_GRANTED'
        ],
        LSL_ConstantVector: [
            'TOUCH_INVALID_TEXCOORD',
            'TOUCH_INVALID_VECTOR',
            'ZERO_VECTOR'
        ],
        LSL_ConstantBroken: [
            'LAND_LARGE_BRUSH',
            'LAND_MEDIUM_BRUSH',
            'LAND_SMALL_BRUSH'
        ],
        LSL_ConstantDeprecated: [
            'ATTACH_LPEC',
            'ATTACH_RPEC',
            'DATA_RATING',
            'OBJECT_ATTACHMENT_GEOMETRY_BYTES',
            'OBJECT_ATTACHMENT_SURFACE_AREA',
            'PRIM_CAST_SHADOWS',
            'PRIM_MATERIAL_LIGHT',
            'PRIM_TYPE_LEGACY',
            'PSYS_SRC_INNERANGLE',
            'PSYS_SRC_OUTERANGLE',
            'VEHICLE_FLAG_NO_FLY_UP'
        ],
        LSL_ConstantUnimplemented: [
            'CHARACTER_MAX_ANGULAR_ACCEL',
            'CHARACTER_MAX_ANGULAR_SPEED',
            'CHARACTER_TURN_SPEED_MULTIPLIER',
            'PERMISSION_CHANGE_JOINTS',
            'PERMISSION_CHANGE_PERMISSIONS',
            'PERMISSION_EXPERIENCE',
            'PERMISSION_RELEASE_OWNERSHIP',
            'PERMISSION_REMAP_CONTROLS',
            'PRIM_PHYSICS_MATERIAL',
            'PSYS_SRC_OBJ_REL_MASK'
        ],
        LSL_FunctionBuiltinFloat: [
            'llAcos',
            'llAngleBetween',
            'llAsin',
            'llAtan2',
            'llCos',
            'llFabs',
            'llFrand',
            'llGetAlpha',
            'llGetAndResetTime',
            'llGetEnergy',
            'llGetGMTclock',
            'llGetMass',
            'llGetMassMKS',
            'llGetMaxScaleFactor',
            'llGetMinScaleFactor',
            'llGetObjectMass',
            'llGetRegionFPS',
            'llGetRegionTimeDilation',
            'llGetSimStats',
            'llGetTextureRot',
            'llGetTime',
            'llGetTimeOfDay',
            'llGetWallclock',
            'llGround',
            'llList2Float',
            'llListStatistics',
            'llLog',
            'llLog10',
            'llPow',
            'llRot2Angle',
            'llSin',
            'llSqrt',
            'llTan',
            'llVecDist',
            'llVecMag',
            'llWater'
        ],
        LSL_FunctionBuiltinInteger: [
            'llAbs',
            'llAgentInExperience',
            'llBase64ToInteger',
            'llCeil',
            'llClearLinkMedia',
            'llClearPrimMedia',
            'llDetectedGroup',
            'llDetectedLinkNumber',
            'llDetectedTouchFace',
            'llDetectedType',
            'llEdgeOfWorld',
            'llFloor',
            'llGetAgentInfo',
            'llGetAttached',
            'llGetFreeMemory',
            'llGetFreeURLs',
            'llGetInventoryNumber',
            'llGetInventoryPermMask',
            'llGetInventoryType',
            'llGetLinkNumber',
            'llGetLinkNumberOfSides',
            'llGetListEntryType',
            'llGetListLength',
            'llGetMemoryLimit',
            'llGetNumberOfPrims',
            'llGetNumberOfSides',
            'llGetObjectPermMask',
            'llGetObjectPrimCount',
            'llGetParcelFlags',
            'llGetParcelMaxPrims',
            'llGetParcelPrimCount',
            'llGetPermissions',
            'llGetRegionAgentCount',
            'llGetRegionFlags',
            'llGetSPMaxMemory',
            'llGetScriptState',
            'llGetStartParameter',
            'llGetStatus',
            'llGetUnixTime',
            'llGetUsedMemory',
            'llGiveMoney',
            'llList2Integer',
            'llListFindList',
            'llListen',
            'llManageEstateAccess',
            'llModPow',
            'llOverMyLand',
            'llReturnObjectsByID',
            'llReturnObjectsByOwner',
            'llRotTarget',
            'llRound',
            'llSameGroup',
            'llScaleByFactor',
            'llScriptDanger',
            'llSetLinkMedia',
            'llSetMemoryLimit',
            'llSetPrimMediaParams',
            'llSetRegionPos',
            'llStringLength',
            'llSubStringIndex',
            'llTarget'
        ],
//      LSL_FunctionBuiltinIntegerBoolean: [],
        LSL_FunctionBuiltinKey: [
            'llAvatarOnLinkSitTarget',
            'llAvatarOnSitTarget',
            'llCreateKeyValue',
            'llDataSizeKeyValue',
            'llDeleteKeyValue',
            'llDetectedKey',
            'llDetectedOwner',
            'llGenerateKey',
            'llGetCreator',
            'llGetInventoryCreator',
            'llGetInventoryKey',
            'llGetKey',
            'llGetLandOwnerAt',
            'llGetLinkKey',
            'llGetNotecardLine',
            'llGetNumberOfNotecardLines',
            'llGetOwner',
            'llGetOwnerKey',
            'llGetPermissionsKey',
            'llHTTPRequest',
            'llKeyCountKeyValue',
            'llKeysKeyValue',
            'llList2Key',
            'llReadKeyValue',
            'llRequestAgentData',
            'llRequestDisplayName',
            'llRequestInventoryData',
            'llRequestSecureURL',
            'llRequestSimulatorData',
            'llRequestURL',
            'llRequestUsername',
            'llSendRemoteData',
            'llTransferLindenDollars',
            'llUpdateKeyValue'
        ],
        LSL_FunctionBuiltinList: [
            'llCSV2List',
            'llCastRay',
            'llDeleteSubList',
            'llGetAgentList',
            'llGetAnimationList',
            'llGetAttachedList',
            'llGetBoundingBox',
            'llGetClosestNavPoint',
            'llGetExperienceDetails',
            'llGetLinkMedia',
            'llGetLinkPrimitiveParams',
            'llGetObjectDetails',
            'llGetParcelDetails',
            'llGetParcelPrimOwners',
            'llGetPhysicsMaterial',
            'llGetPrimMediaParams',
            'llGetPrimitiveParams',
            'llGetStaticPath',
            'llJson2List',
            'llList2List',
            'llList2ListStrided',
            'llListInsertList',
            'llListRandomize',
            'llListReplaceList',
            'llListSort',
            'llParcelMediaQuery',
            'llParseString2List',
            'llParseStringKeepNulls'
        ],
        LSL_FunctionBuiltinRotation: [
            'llAxes2Rot',
            'llAxisAngle2Rot',
            'llDetectedRot',
            'llEuler2Rot',
            'llGetCameraRot',
            'llGetLocalRot',
            'llGetRootRotation',
            'llGetRot',
            'llList2Rot',
            'llRotBetween'
        ],
        LSL_FunctionBuiltinString: [
            'llBase64ToString',
            'llDeleteSubString',
            'llDetectedName',
            'llDumpList2String',
            'llEscapeURL',
            'llGetAgentLanguage',
            'llGetAnimation',
            'llGetAnimationOverride',
            'llGetDate',
            'llGetDisplayName',
            'llGetEnv',
            'llGetExperienceErrorMessage',
            'llGetHTTPHeader',
            'llGetInventoryName',
            'llGetLinkName',
            'llGetObjectDesc',
            'llGetObjectName',
            'llGetParcelMusicURL',
            'llGetRegionName',
            'llGetScriptName',
            'llGetSimulatorHostname',
            'llGetSubString',
            'llGetTexture',
            'llGetTimestamp',
            'llGetUsername',
            'llInsertString',
            'llIntegerToBase64',
            'llJsonGetValue',
            'llJsonSetValue',
            'llJsonValueType',
            'llKey2Name',
            'llList2CSV',
            'llList2Json',
            'llList2String',
            'llMD5String',
            'llSHA1String',
            'llStringToBase64',
            'llStringTrim',
            'llToLower',
            'llToUpper',
            'llUnescapeURL',
            'llXorBase64'
        ],
        LSL_FunctionBuiltinVector: [
            'llDetectedGrab',
            'llDetectedPos',
            'llDetectedTouchBinormal',
            'llDetectedTouchNormal',
            'llDetectedTouchPos',
            'llDetectedTouchST',
            'llDetectedTouchUV',
            'llDetectedVel',
            'llGetAccel',
            'llGetAgentSize',
            'llGetCameraPos',
            'llGetCenterOfMass',
            'llGetColor',
            'llGetForce',
            'llGetGeometricCenter',
            'llGetLocalPos',
            'llGetOmega',
            'llGetPos',
            'llGetRegionCorner',
            'llGetRootPosition',
            'llGetScale',
            'llGetSunDirection',
            'llGetTextureOffset',
            'llGetTextureScale',
            'llGetTorque',
            'llGetVel',
            'llGroundContour',
            'llGroundNormal',
            'llGroundSlope',
            'llList2Vector',
            'llRot2Axis',
            'llRot2Euler',
            'llRot2Fwd',
            'llRot2Left',
            'llRot2Up',
            'llVecNorm',
            'llWind'
        ],
        LSL_FunctionBuiltinVoid: [
            'llAddToLandBanList',
            'llAddToLandPassList',
            'llAdjustSoundVolume',
            'llAllowInventoryDrop',
            'llApplyImpulse',
            'llApplyRotationalImpulse',
            'llAttachToAvatar',
            'llAttachToAvatarTemp',
            'llBreakAllLinks',
            'llBreakLink',
            'llClearCameraParams',
            'llCloseRemoteDataChannel',
            'llCollisionFilter',
            'llCollisionSound',
            'llCreateCharacter',
            'llCreateLink',
            'llDeleteCharacter',
            'llDetachFromAvatar',
            'llDialog',
            'llDie',
            'llEjectFromLand',
            'llEmail',
            'llEvade',
            'llExecCharacterCmd',
            'llFleeFrom',
            'llForceMouselook',
            'llGetNextEmail',
            'llGiveInventory',
            'llGiveInventoryList',
            'llGroundRepel',
            'llHTTPResponse',
            'llInstantMessage',
            'llLinkParticleSystem',
            'llLinkSitTarget',
            'llListenControl',
            'llListenRemove',
            'llLoadURL',
            'llLookAt',
            'llLoopSound',
            'llLoopSoundMaster',
            'llLoopSoundSlave',
            'llMapDestination',
            'llMessageLinked',
            'llMinEventDelay',
            'llModifyLand',
            'llMoveToTarget',
            'llNavigateTo',
            'llOffsetTexture',
            'llOpenRemoteDataChannel',
            'llOwnerSay',
            'llParcelMediaCommandList',
            'llParticleSystem',
            'llPassCollisions',
            'llPassTouches',
            'llPatrolPoints',
            'llPlaySound',
            'llPlaySoundSlave',
            'llPreloadSound',
            'llPursue',
            'llPushObject',
            'llRegionSay',
            'llRegionSayTo',
            'llReleaseControls',
            'llReleaseURL',
            'llRemoteDataReply',
            'llRemoteLoadScriptPin',
            'llRemoveFromLandBanList',
            'llRemoveFromLandPassList',
            'llRemoveInventory',
            'llRemoveVehicleFlags',
            'llRequestExperiencePermissions',
            'llRequestPermissions',
            'llResetAnimationOverride',
            'llResetLandBanList',
            'llResetLandPassList',
            'llResetOtherScript',
            'llResetScript',
            'llResetTime',
            'llRezAtRoot',
            'llRezObject',
            'llRotLookAt',
            'llRotTargetRemove',
            'llRotateTexture',
            'llSay',
            'llScaleTexture',
            'llScriptProfiler',
            'llSensor',
            'llSensorRemove',
            'llSensorRepeat',
            'llSetAlpha',
            'llSetAngularVelocity',
            'llSetAnimationOverride',
            'llSetBuoyancy',
            'llSetCameraAtOffset',
            'llSetCameraEyeOffset',
            'llSetCameraParams',
            'llSetClickAction',
            'llSetColor',
            'llSetContentType',
            'llSetDamage',
            'llSetForce',
            'llSetForceAndTorque',
            'llSetHoverHeight',
            'llSetKeyframedMotion',
            'llSetLinkAlpha',
            'llSetLinkCamera',
            'llSetLinkColor',
            'llSetLinkPrimitiveParams',
            'llSetLinkPrimitiveParamsFast',
            'llSetLinkTexture',
            'llSetLinkTextureAnim',
            'llSetLocalRot',
            'llSetObjectDesc',
            'llSetObjectName',
            'llSetParcelMusicURL',
            'llSetPayPrice',
            'llSetPhysicsMaterial',
            'llSetPos',
            'llSetPrimitiveParams',
            'llSetRemoteScriptAccessPin',
            'llSetRot',
            'llSetScale',
            'llSetScriptState',
            'llSetSitText',
            'llSetSoundQueueing',
            'llSetSoundRadius',
            'llSetStatus',
            'llSetText',
            'llSetTexture',
            'llSetTextureAnim',
            'llSetTimerEvent',
            'llSetTorque',
            'llSetTouchText',
            'llSetVehicleFlags',
            'llSetVehicleFloatParam',
            'llSetVehicleRotationParam',
            'llSetVehicleType',
            'llSetVehicleVectorParam',
            'llSetVelocity',
            'llShout',
            'llSitTarget',
            'llSleep',
            'llStartAnimation',
            'llStopAnimation',
            'llStopHover',
            'llStopLookAt',
            'llStopMoveToTarget',
            'llStopSound',
            'llTakeControls',
            'llTargetOmega',
            'llTargetRemove',
            'llTeleportAgent',
            'llTeleportAgentGlobalCoords',
            'llTeleportAgentHome',
            'llTextBox',
            'llTriggerSound',
            'llTriggerSoundLimited',
            'llUnSit',
            'llUpdateCharacter',
            'llVolumeDetect',
            'llWanderWithin',
            'llWhisper'
        ],
        LSL_FunctionDeprecated: [
            'llClearExperiencePermissions',
            'llCloud',
            'llGetExperienceList',
            'llMakeExplosion',
            'llMakeFire',
            'llMakeFountain',
            'llMakeSmoke',
            'llRemoteDataSetRegion',
            'llSound',
            'llSoundPreload',
            'llXorBase64Strings',
            'llXorBase64StringsCorrect'
        ],
        LSL_FunctionDocumentation: [
            'print'
        ],
        LSL_FunctionGodmode: [
            'llGodLikeRezObject',
            'llSetInventoryPermMask',
            'llSetObjectPermMask'
        ],
        LSL_FunctionUnimplemented: [
            'llCollisionSprite',
            'llPointAt',
            'llRefreshPrimURL',
            'llReleaseCamera',
            'llRemoteLoadScript',
            'llSetPrimURL',
            'llStopPointAt',
            'llTakeCamera'
        ],
        LSL_Illegal: [
            'event'
        ],

//  @TODO:
//      vector-identifier.xyz
//      <float, float, float>.xyz
//      rotation-identifier.xyzs
//      <float, float, float, float>.xyzs

        tokenizer: {
            root: [
                ['(?:(state)\s+[A-Za-z_]\w*|default)': 'entity.name.class.lsl'],
                ['\b([a-zA-Z_]\w*)\b', { cases: {
                    '@LSL_Illegal': 'invalid.illegal.lsl',
                    '@LSL_FlowControl': 'keyword.control.flow.lsl',
                    '@LSL_Event': 'support.function.event.lsl',
                    '@LSL_StorageType': 'storage.type.lsl',
                    '@LSL_FunctionBuiltinFloat': 'support.function.builtin.float.lsl',
                    '@LSL_FunctionBuiltinInteger': 'support.function.builtin.integer.lsl',
//                  '@LSL_FunctionBuiltinIntegerBoolean': 'support.function.builtin.integer.boolean.lsl',
                    '@LSL_FunctionBuiltinKey': 'support.function.builtin.key.lsl',
                    '@LSL_FunctionBuiltinList': 'support.function.builtin.list.lsl',
                    '@LSL_FunctionBuiltinRotation': 'support.function.builtin.rotation.lsl',
                    '@LSL_FunctionBuiltinString': 'support.function.builtin.string.lsl',
                    '@LSL_FunctionBuiltinVector': 'support.function.builtin.vector.lsl',
                    '@LSL_FunctionBuiltinVoid': 'support.function.builtin.void.lsl',
                    '@LSL_FunctionDocumentation': 'reserved.function.builtin.doc.lsl',
                    '@LSL_FunctionGodmode': 'reserved.support.function.builtin.god-mode.lsl',
                    '@LSL_FunctionUnimplemented': 'invalid.unimplemented.support.function.builtin.lsl',
                    '@LSL_FunctionDeprecated': 'invalid.deprecated.support.function.builtin.lsl',
                    '@LSL_ConstantFloat': 'constant.numeric.float.lsl',
                    '@LSL_ConstantInteger': 'constant.numeric.integer.lsl',
                    '@LSL_ConstantIntegerBoolean': 'constant.numeric.integer.boolean.lsl',
                    '@LSL_ConstantRotation': 'constant.rotation.lsl',
                    '@LSL_ConstantString': 'constant.string.lsl',
                    '@LSL_ConstantVector': 'constant.vector.lsl',
                    '@LSL_ConstantBroken': 'invalid.broken.constant.lsl',
                    '@LSL_ConstantUnimplemented': 'invalid.unimplemented.constant.lsl',
                    '@LSL_ConstantDeprecated': 'invalid.deprecated.constant.lsl',
//                  '@keywords': { token: 'keyword.$0.lsl' },
                    '@default': 'identifier.lsl' } }],
                { include: '@whitespace' },
//              ['\[\[.*\]\]', 'annotation.lsl'],
//              ['^\s*#\w+', 'keyword.lsl'],
                ['[{}()\[\]]', '@brackets'],
//              ['[<>](?!@symbols)', '@brackets'],
                ['@symbols', { cases: {
                    '@operators': 'delimiter.lsl',
                    '@default': '' } }],
                ['\d*\d+[eE]([\-]?\d+)?', 'number.float.lsl'],
                ['\d*\.\d+([eE][\-]?\d+)?', 'number.float.lsl'],
                ['0[xX][0-9a-fA-F]*', 'number.hex.lsl'],
//              ['0[0-7]*', 'number.octal.lsl'],
//              ['0[bB][0-1]*', 'number.binary.lsl'],
                ['\d[\d]*\d', 'number.lsl'],
                ['\d', 'number.lsl'],
                ['[;,]', 'delimiter.lsl'],
//              ['"([^"\\]|\\.)*$', 'string.invalid.lsl'],
                ['"', 'string.quoted.double.begin.lsl', '@string'],
//              ['"[^\\"]"', 'string.lsl'],
//              ['(")(@escapes)(")', ['string.lsl', 'string.escape.lsl', 'string.lsl']],
//              ['"', 'string.invalid.lsl']
            ],
            whitespace: [
                ['[ \t\n]+', ''],
                ['\/\/.*$', 'comment.line.double-slash.lsl'],
                ['\/\*\*(?!\/)', 'comment.block.doc.begin.lsl', '@commentBlockDoc'],
                ['\/\*', 'comment.block.begin.lsl', '@commentBlock']
            ],
            commentBlock: [
                ['[^\/*]+', 'comment.block.lsl'],
                ['\*\/', 'comment.block.end.lsl', '@pop'],
                ['[\/*]', 'comment.block.lsl']
            ],
            commentBlockDoc: [
                ['[^\/*]+', 'comment.block.doc.lsl'],
                ['\*\/', 'comment.block.doc.end.lsl', '@pop'],
                ['[\/*]', 'comment.block.doc.lsl']
            ],
            string: [
                ['[^\\"]+', 'string.quoted.double.lsl'],
                ['@escapes', 'string.escape.lsl'],
                ['\\.', 'invalid.illegal.string.escape.lsl'],
                ['"', 'string.quoted.double.end.lsl', '@pop']
            ]
        }
    };
});
